# Sol RTMP Server Configuration
# 필요한 설정만 작성하면 됩니다. 
# 설정하지 않은 항목은 기본값을 사용합니다.

# RTMP 서버 설정 (기존)
rtmp:
  port: 1935                    # 기본값: 1935

# RTMP2 서버 설정 (새로운 pkg/media 아키텍처)
rtmp2:
  port: 1936                    # 기본값: 1936

# RTSP 서버 설정
rtsp:
  port: 554                     # 기본값: 554
  timeout: 60                   # 기본값: 60 (초)

# API 서버 설정
api:
  port: 8080                    # 기본값: 8080

# 로깅 설정
logging:
  level: info                   # 기본값: info (debug, info, warn, error)

# 스트림 관련 설정
stream:
  gop_cache_size: 10           # 기본값: 10 (비디오 GOP 캐시 프레임 수)
  max_players_per_stream: 100  # 기본값: 100 (스트림별 최대 시청자 수, 0=무제한)
